name: RG25
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - pip
  - pip:
      - cv2_enumerate_cameras
      - pyapriltags
      - pyserial
      - nicegui
      - asyncio
      - pyee
      - psutil
      - Pillow
