// Auto-generated. DO NOT EDIT MANUALLY.
// Generated at UTC 2025-09-16 15:39:31
#ifndef PROTOCOL_DEFS_H
#define PROTOCOL_DEFS_H
#include <stdint.h>

#define PROTOCOL_DATA_VER_FULL  20250916153931ULL
#define PROTOCOL_DATA_VER       0x4B

// MSG roles
#define MSG_PC_TO_MCU 0x01
#define MSG_MCU_TO_PC 0x02

// Variable IDs (T in TLV)
#define VAR_FRICTION_WHEEL_SPEED 0x01
#define VAR_GRIPPER_GRASP_DEBUG 0x02
#define VAR_FRICTION_WHEEL_STOP_DEBUG 0x0A
#define VAR_GRIPPER_LOAD_DART 0x0F
#define VAR_GRIPPER_TAG_Y 0x15
#define VAR_DART_PUSH_BACKWARD_DEBUG 0x19
#define VAR_BASE_MOVE_BACKWARD_FAST 0x21
#define VAR_GRIPPER_READY 0x2D
#define VAR_BASE_ROTATE_CW_FAST 0x36
#define VAR_FIRE_ONCE 0x41
#define VAR_BASE_MOVE_FORWARD_FAST 0x5B
#define VAR_BASE_ROTATE_CW_SLOW 0x5D
#define VAR_DART_PUSH_STOP_DEBUG 0x64
#define VAR_TEST_VAR_U8 0x67
#define VAR_GRIPPER_TAG_X 0x69
#define VAR_DATA_ERROR 0x6A
#define VAR_BASE_STOP 0x7B
#define VAR_BASE_ROTATE_CCW_FAST 0x83
#define VAR_GRIPPER_RELEASE_DEBUG 0x84
#define VAR_TEST_VAR_F32 0x88
#define VAR_DART_PUSH_ONCE_DEBUG 0x89
#define VAR_BASE_MOVE_FORWARD_SLOW 0x8C
#define VAR_BASE_ROTATE_CCW_SLOW 0x94
#define VAR_BASE_MOVE_BACKWARD_SLOW 0x99
#define VAR_BASE_MOVE_LEFT_SLOW 0x9A
#define VAR_DART_PUSH_FORWARD_DEBUG 0x9D
#define VAR_GRIPPER_RELAX 0x9F
#define VAR_DART_PUSH_RESET_DEBUG 0xAB
#define VAR_FRICTION_WHEEL_START_DEBUG 0xB2
#define VAR_GRIPPER_GRASP_DART 0xBA
#define VAR_GRIPPER_TAG_Z 0xC4
#define VAR_BASE_MOVE_LEFT_FAST 0xC5
#define VAR_BASE_MOVE_RIGHT_SLOW 0xC9
#define VAR_BASE_MOVE_RIGHT_FAST 0xCA
#define VAR_HEARTBEAT 0xD1
#define VAR_TURRET_ANGLE_YAW 0xE1
#define VAR_TEST_VAR_U16 0xE6

// Fixed sizes (only for fixed-width variables); others are variable-length per TLV L
#define VAR_FRICTION_WHEEL_SPEED_SIZE 4
#define VAR_GRIPPER_GRASP_DEBUG_SIZE 1
#define VAR_FRICTION_WHEEL_STOP_DEBUG_SIZE 1
#define VAR_GRIPPER_LOAD_DART_SIZE 1
#define VAR_GRIPPER_TAG_Y_SIZE 4
#define VAR_DART_PUSH_BACKWARD_DEBUG_SIZE 1
#define VAR_BASE_MOVE_BACKWARD_FAST_SIZE 1
#define VAR_GRIPPER_READY_SIZE 1
#define VAR_BASE_ROTATE_CW_FAST_SIZE 1
#define VAR_FIRE_ONCE_SIZE 1
#define VAR_BASE_MOVE_FORWARD_FAST_SIZE 1
#define VAR_BASE_ROTATE_CW_SLOW_SIZE 1
#define VAR_DART_PUSH_STOP_DEBUG_SIZE 1
#define VAR_TEST_VAR_U8_SIZE 1
#define VAR_GRIPPER_TAG_X_SIZE 4
#define VAR_DATA_ERROR_SIZE 1
#define VAR_BASE_STOP_SIZE 1
#define VAR_BASE_ROTATE_CCW_FAST_SIZE 1
#define VAR_GRIPPER_RELEASE_DEBUG_SIZE 1
#define VAR_TEST_VAR_F32_SIZE 4
#define VAR_DART_PUSH_ONCE_DEBUG_SIZE 1
#define VAR_BASE_MOVE_FORWARD_SLOW_SIZE 1
#define VAR_BASE_ROTATE_CCW_SLOW_SIZE 1
#define VAR_BASE_MOVE_BACKWARD_SLOW_SIZE 1
#define VAR_BASE_MOVE_LEFT_SLOW_SIZE 1
#define VAR_DART_PUSH_FORWARD_DEBUG_SIZE 1
#define VAR_GRIPPER_RELAX_SIZE 1
#define VAR_DART_PUSH_RESET_DEBUG_SIZE 1
#define VAR_FRICTION_WHEEL_START_DEBUG_SIZE 1
#define VAR_GRIPPER_GRASP_DART_SIZE 1
#define VAR_GRIPPER_TAG_Z_SIZE 4
#define VAR_BASE_MOVE_LEFT_FAST_SIZE 1
#define VAR_BASE_MOVE_RIGHT_SLOW_SIZE 1
#define VAR_BASE_MOVE_RIGHT_FAST_SIZE 1
#define VAR_HEARTBEAT_SIZE 1
#define VAR_TURRET_ANGLE_YAW_SIZE 4
#define VAR_TEST_VAR_U16_SIZE 2

static const uint8_t VAR_SIZE_TABLE[256] = {
    [VAR_FRICTION_WHEEL_SPEED] = 4,
    [VAR_GRIPPER_GRASP_DEBUG] = 1,
    [VAR_FRICTION_WHEEL_STOP_DEBUG] = 1,
    [VAR_GRIPPER_LOAD_DART] = 1,
    [VAR_GRIPPER_TAG_Y] = 4,
    [VAR_DART_PUSH_BACKWARD_DEBUG] = 1,
    [VAR_BASE_MOVE_BACKWARD_FAST] = 1,
    [VAR_GRIPPER_READY] = 1,
    [VAR_BASE_ROTATE_CW_FAST] = 1,
    [VAR_FIRE_ONCE] = 1,
    [VAR_BASE_MOVE_FORWARD_FAST] = 1,
    [VAR_BASE_ROTATE_CW_SLOW] = 1,
    [VAR_DART_PUSH_STOP_DEBUG] = 1,
    [VAR_TEST_VAR_U8] = 1,
    [VAR_GRIPPER_TAG_X] = 4,
    [VAR_DATA_ERROR] = 1,
    [VAR_BASE_STOP] = 1,
    [VAR_BASE_ROTATE_CCW_FAST] = 1,
    [VAR_GRIPPER_RELEASE_DEBUG] = 1,
    [VAR_TEST_VAR_F32] = 4,
    [VAR_DART_PUSH_ONCE_DEBUG] = 1,
    [VAR_BASE_MOVE_FORWARD_SLOW] = 1,
    [VAR_BASE_ROTATE_CCW_SLOW] = 1,
    [VAR_BASE_MOVE_BACKWARD_SLOW] = 1,
    [VAR_BASE_MOVE_LEFT_SLOW] = 1,
    [VAR_DART_PUSH_FORWARD_DEBUG] = 1,
    [VAR_GRIPPER_RELAX] = 1,
    [VAR_DART_PUSH_RESET_DEBUG] = 1,
    [VAR_FRICTION_WHEEL_START_DEBUG] = 1,
    [VAR_GRIPPER_GRASP_DART] = 1,
    [VAR_GRIPPER_TAG_Z] = 4,
    [VAR_BASE_MOVE_LEFT_FAST] = 1,
    [VAR_BASE_MOVE_RIGHT_SLOW] = 1,
    [VAR_BASE_MOVE_RIGHT_FAST] = 1,
    [VAR_HEARTBEAT] = 1,
    [VAR_TURRET_ANGLE_YAW] = 4,
    [VAR_TEST_VAR_U16] = 2,
    // others default to 0 (variable-length)
};

#endif // PROTOCOL_DEFS_H

